From 5e57f6d2462c2983ca160f6c1f971a1a92a5a4a4 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Andr=C3=A9=20=22decko=22=20de=20Brito?= <decko@redhat.com>
Date: Fri, 25 Apr 2025 11:46:36 -0300
Subject: [PATCH] Raise an exception for any dispatched task.

---
 pulpcore/tasking/tasks.py | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/pulpcore/tasking/tasks.py b/pulpcore/tasking/tasks.py
index 16616214b..67ef17ac8 100644
--- a/pulpcore/tasking/tasks.py
+++ b/pulpcore/tasking/tasks.py
@@ -14,6 +14,9 @@ from django.conf import settings
 from django.db import connection, transaction
 from django.db.models import Model, Max
 from django_guid import get_guid
+
+from rest_framework.exceptions import APIException
+
 from pulpcore.app.apps import MODULE_PLUGIN_VERSIONS
 from pulpcore.app.models import Task, TaskGroup
 from pulpcore.app.util import current_task, get_domain, get_prn
@@ -147,6 +150,12 @@ def dispatch(
     Raises:
         ValueError: When `resources` is an unsupported type.
     """
+    class ServiceUnavailable(APIException):
+        status_code = 503
+        default_detail = 'Service temporarily unavailable, try again later.'
+        default_code = 'service_unavailable' 
+        
+    raise ServiceUnavailable()
 
     assert deferred or immediate, "A task must be at least `deferred` or `immediate`."
 
-- 
2.49.0

